config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "toppages#index"
  resources :toppages, only: :index
  resources :users, only: [:edit, :update, :index]
  resources :messages, only: [:index, :new, :create]
  resources :features, only: [:index, :edit, :update, :new, :create] do
    resources :weights, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :weights
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :weights
  has_many :features
  validates :name, presence: true, uniqueness: true
  
end

app/models/weight.rb
class Weight < ApplicationRecord
  belongs_to :user
  belongs_to :feature
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def index
    @features = current_user.features
    @chart = current_user.weights.pluck(:created_at, :dailyweight)
  end
  
  def new
    @feature = Feature.new
  end

  def create
    Feature.create(feature_params)
  end

  def edit
    @feature = Feature.find(params[:id])
  end

  def update
    @feature = Feature.find(params[:id])
    if @feature.update(feature_params)
      redirect_to features_path
    else
      render :edit
    end
  end

  private
  def feature_params
    params.require(:feature).permit(:length, :weight , :age, :goalweight, :goaldate).merge(user_id: current_user.id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    Message.create(message_params)
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to mypages_path
    else
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  def new
    @weight = Weight.new
  end

  def create
    weight = Weight.create(weight_params)
    redirect_to features_path(current_user)
  end

  private
  
  def weight_params
    params.require(:weight).permit(:dailyweight).merge(user_id: current_user.id, feature_id: params[:feature_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/features/_feature.html.haml
.BottomContents__left
  %p= "目標 #{feature.goalweight} kg"
  %p= "現在 #{feature.weight} kg"
  %p= "残り #{feature.weight - feature.goalweight}kg"

.BottomContents__right
  - kcal = 13.4 * feature.weight + 4.8 * feature.length - 5.677 * feature.age + 88.362  
  %p= "基礎代謝 #{kcal} kcal"
  %p= "1日の目安#{kcal-100}kcal"
  %p= "目標まであと #{feature.goaldate} 日"

app/views/features/create.html.haml
.ContentsRow
  .ContentsRow__success
    登録が完了しました
  .ContentsRow__back
    = link_to features_path(current_user.id) do
      マイページへ戻る

app/views/features/edit.html.haml
.TopMessage
  %h1.message 登録情報の変更
.Form
  .Form__Contents
    = form_with model: @feature, class: 'Form_input', local: true do |f|
      = f.number_field :length, placeholder: '身長', class: 'input'
      = f.number_field :weight, placeholder: '体重', class: 'input'
      = f.number_field :age, placeholder: '年齢', class: 'input'
      = f.number_field :goalweight, placeholder: '目標体重', class: 'input'
      = f.datetime_field :goaldate, placeholder: '目標日', class: 'input'
      = f.submit '登録', class: 'input'

app/views/features/index.html.haml
.UpperContents
  .UpperContents__userName
    = current_user.name
  .UpperContents__topmessage
    体重の変化
  .UpperContents__rightField
    .UpperContents__information
      = link_to edit_user_path(current_user), class: 'Buttons' do
        = icon('fas', 'cog')
      = link_to edit_feature_path(current_user), class: 'Buttons' do
        編集
      = link_to new_feature_path(current_user), class: 'Buttons' do
        登録      
= line_chart @chart, discrete: true, width: "100%", height: "500px"
.BottomContents
  = render partial: "feature", collection: @features
.BottomMain
  =link_to new_feature_weight_path(current_user) do
    %input.Link{ type: 'button', value: '今日の体重を入力' }

app/views/features/new.html.haml
.TopMessage
  %h1.message 新規登録
.Form
  .Form__Contents
    = form_with model: @feature, class: 'Form_input', local: true do |f|
      = f.number_field :length, placeholder: '身長', class: 'input'
      = f.number_field :weight, placeholder: '体重', class: 'input'
      = f.number_field :age, placeholder: '年齢', class: 'input'
      = f.number_field :goalweight, placeholder: '目標体重', class: 'input'
      = f.datetime_field :goaldate, placeholder: '目標日', class: 'input'
      = f.submit '登録', class: 'input'

app/views/features/update.html.haml
.ContentsRow
  .ContentsRow__success
    登録が完了しました
  .ContentsRow__back
    = link_to features_path(current_user) do
      マイページへ戻る

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Healthfit
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .Header
      = link_to root_path, class: "Header__topButton" do
        HealthFit
      .RightGroup  
        = link_to messages_path(current_user), class: "RightGroup__baButton" do
          B.A
        = link_to new_message_path(current_user), class: "RightGroup__myphots" do
          = icon('far', 'image', class: 'RightGroup__icon')
    = yield

app/views/messages/_message.html.haml
.MessageBox
  .MessageInfo
    .MessageInfo__username
      = current_user.name
    .MessageInfo__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .Message
    - if message.content.present?
      %p.Message__content
        = message.content
    = image_tag message.image.url, class: 'Message__image' if message.image.present?

app/views/messages/create.html.haml
.ContentsRow
  .ContentsRow__success
    投稿が完了しました
  .ContentsRow__back
    = link_to messages_path do
      投稿一覧へ戻る

app/views/messages/index.html.haml
.Wrapper
  .Wrapper__ImageContents
    .Wrapper_ImageContent
      = render @messages

app/views/messages/new.html.haml
.MessageForm
  = form_with model: @message, url: "/messages", html: {class: "FormText"}, local: true do |f|
    = f.text_field :content, class: 'FormText__inputText', placeholder: 'メッセージを入力'
    = f.label :image, class: 'FormText__image' do
      = icon('far', 'image', class: 'FormText__icon')
      = f.file_field :image, class: 'FormText__file'
    = f.submit '送信', class: 'FormText__submitBtn'

app/views/toppages/index.html.haml
.TopContents      
  .TopContents__BackgroundImage
    = image_tag 'image.jpg', alt: 'run', height: '100%', width: '100%', class: 'image'
  .TopContents__message
    楽しく生きる
  .TopContents__submessage
    毎日の体重を管理しよう
.Main
  .Main__Contents
    =link_to features_path(current_user) do
      %input.Link{ type: 'button', value: 'さあ、始めよう' }

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'

app/views/users/index.html.haml
.UpperContents
  .UpperContents__topmessage
    体重の変化
= line_chart @chart, width: "900px", height: "500px"
.BottomContents
  .BottomContents__left
    %p 目標 65 kg
    %p 現在 70 kg
    %p 残り 5 kg
  .BottomContents__right
    %p 基礎代謝 1500 kcal
    %p 1日の目安 1300kcal
    %p 目標まであと 30 日
.BottomMain
  %form.BottomMain__Weight
    %input.weightBtn{url: '#', type: 'number', placeholder: '今日の体重を入力'}
    %input.submitBtn{url: '#', type: 'submit', value: '登録する'}

app/views/weights/create.html.haml
.ContentsRow
  .ContentsRow__success
    登録が完了しました
  .ContentsRow__back
    = link_to features_path(current_user) do
      マイページへ戻る

app/views/weights/new.html.haml
.Main
  .Main__Contents
    = form_with model: @weight, url: feature_weights_path, method: :post, html: {class: "BottomMain__Weight"}, local: true do |f|
      = f.number_field :dailyweight, class: 'weightBtn', placeholder: '今日の体重を入力'
      = f.submit '登録する', class: 'submitBtn'